export const systemConfig = {
  integumentary: { label: "Tegumentario", color: "#e8b08d", opacity: 1 },
  skeletal: { label: "Oseo", color: "#f4f0df", opacity: 1 },
  muscular: { label: "Muscular", color: "#b73532", opacity: 1 },
  nervous: { label: "Nervioso", color: "#f0cf3e", opacity: 1 },
  circulatory: { label: "Circulatorio", color: "#c92f3a", opacity: 1 },
  respiratory: { label: "Respiratorio", color: "#67c7d8", opacity: 1 },
  digestive: { label: "Digestivo", color: "#c9792e", opacity: 1 },
  urinary: { label: "Urinario", color: "#d6bb4a", opacity: 1 },
  endocrine: { label: "Endocrino", color: "#8f6cc8", opacity: 1 },
  lymphatic: { label: "Linfatico", color: "#69b86f", opacity: 1 },
  reproductiveMale: { label: "Reprod. masc.", color: "#6c8fc7", opacity: 1 },
  reproductiveFemale: { label: "Reprod. fem.", color: "#d4719c", opacity: 1 },
};

export const systemOrder = [
  "integumentary",
  "skeletal",
  "muscular",
  "nervous",
  "circulatory",
  "respiratory",
  "digestive",
  "urinary",
  "endocrine",
  "lymphatic",
  "reproductiveMale",
  "reproductiveFemale",
];

export const systemDetails = {
  integumentary: {
    title: "Sistema tegumentario",
    summary: "Recubre, protege y comunica al cuerpo con el exterior.",
    function: "Protege, regula temperatura y detecta estimulos como presion, dolor y calor.",
    organs: ["Piel", "Cabello", "Unas", "Glandulas sudoriparas", "Glandulas sebaceas"],
    keyFact: "La piel es el organo mas extenso del cuerpo.",
    question: "Como ayuda la piel a regular la temperatura?",
    miniSummary: "Es la primera defensa fisica del organismo.",
  },
  skeletal: {
    title: "Sistema oseo",
    summary: "Sostiene el cuerpo, protege organos y permite movimiento.",
    function: "Da soporte, protege organos y trabaja con musculos para mover el cuerpo.",
    organs: ["Craneo", "Columna vertebral", "Costillas", "Pelvis", "Huesos largos"],
    keyFact: "La medula osea produce celulas sanguineas.",
    question: "Que organos protege la caja toracica?",
    miniSummary: "Da soporte, proteccion y puntos de anclaje para los musculos.",
  },
  muscular: {
    title: "Sistema muscular",
    summary: "Genera movimiento, postura y fuerza.",
    function: "Sus contracciones generan movimiento, postura y calor corporal.",
    organs: ["Musculos esqueleticos", "Tendones", "Diafragma", "Musculos faciales"],
    keyFact: "El diafragma es un musculo esencial para la respiracion.",
    question: "Como se mueve un hueso cuando un musculo se contrae?",
    miniSummary: "Convierte energia quimica en fuerza y movimiento.",
  },
  nervous: {
    title: "Sistema nervioso",
    summary: "Coordina informacion, respuestas y aprendizaje.",
    function: "Recibe informacion, la procesa y coordina respuestas rapidas.",
    organs: ["Cerebro", "Cerebelo", "Medula espinal", "Nervios perifericos"],
    keyFact: "La medula espinal comunica el encefalo con gran parte del cuerpo.",
    question: "Por que sacamos la mano rapido ante algo caliente?",
    miniSummary: "Es el sistema de control y comunicacion rapida.",
  },
  circulatory: {
    title: "Sistema circulatorio",
    summary: "Transporta sangre, gases, nutrientes y desechos.",
    function: "El corazon impulsa sangre para llevar oxigeno, nutrientes y retirar desechos.",
    organs: ["Corazon", "Arterias", "Venas", "Capilares", "Sangre"],
    keyFact: "En los capilares ocurre el intercambio con los tejidos.",
    question: "Por que los musculos necesitan sangre?",
    miniSummary: "Es la red de transporte del organismo.",
  },
  respiratory: {
    title: "Sistema respiratorio",
    summary: "Incorpora oxigeno y elimina dioxido de carbono.",
    function: "Lleva aire a los pulmones para intercambiar oxigeno y dioxido de carbono.",
    organs: ["Nariz", "Laringe", "Traquea", "Bronquios", "Pulmones", "Diafragma"],
    keyFact: "El oxigeno pasa de los pulmones a la sangre.",
    question: "Como se relacionan los sistemas respiratorio y circulatorio?",
    miniSummary: "Permite el intercambio de gases necesario para obtener energia.",
  },
  digestive: {
    title: "Sistema digestivo",
    summary: "Transforma alimentos en nutrientes aprovechables.",
    function: "Descompone alimentos, absorbe nutrientes y elimina residuos.",
    organs: ["Boca", "Esofago", "Estomago", "Higado", "Pancreas", "Intestinos"],
    keyFact: "El intestino delgado absorbe la mayor parte de nutrientes.",
    question: "Por que necesitamos digerir los alimentos?",
    miniSummary: "Procesa alimentos para alimentar a las celulas.",
  },
  urinary: {
    title: "Sistema urinario",
    summary: "Filtra la sangre y regula agua y sales.",
    function: "Filtra sangre, produce orina y regula agua y sales.",
    organs: ["Rinones", "Ureteres", "Vejiga", "Uretra"],
    keyFact: "Los rinones ayudan a mantener el equilibrio interno.",
    question: "Por que filtrar la sangre es importante para todas las celulas?",
    miniSummary: "Limpia la sangre y mantiene equilibrio interno.",
  },
  endocrine: {
    title: "Sistema endocrino",
    summary: "Regula procesos mediante hormonas.",
    function: "Libera hormonas que regulan crecimiento, metabolismo y reproduccion.",
    organs: ["Hipofisis", "Tiroides", "Pancreas endocrino", "Suprarrenales", "Gonadas"],
    keyFact: "Las hormonas son mensajes quimicos.",
    question: "Por que las hormonas viajan por la sangre?",
    miniSummary: "Coordina funciones con mensajes quimicos.",
  },
  lymphatic: {
    title: "Sistema linfatico",
    summary: "Participa en defensas y retorno de liquidos.",
    function: "Transporta linfa, filtra microorganismos y recupera liquidos.",
    organs: ["Vasos linfaticos", "Ganglios linfaticos", "Bazo", "Timo", "Amigdalas"],
    keyFact: "Los ganglios pueden inflamarse durante infecciones.",
    question: "Que funcion cumplen los ganglios?",
    miniSummary: "Ayuda a defender y drenar el organismo.",
  },
  reproductiveMale: {
    title: "Aparato reproductor masculino",
    summary: "Produce y transporta espermatozoides.",
    function: "Produce espermatozoides y ayuda a transportarlos.",
    organs: ["Testiculos", "Epididimo", "Conductos deferentes", "Prostata", "Pene"],
    keyFact: "Los testiculos producen espermatozoides y hormonas.",
    question: "Por que la reproduccion requiere celulas especializadas llamadas gametos?",
    miniSummary: "Produce gametos masculinos y participa en la reproduccion.",
  },
  reproductiveFemale: {
    title: "Aparato reproductor femenino",
    summary: "Produce ovulos y posibilita gestacion.",
    function: "Produce ovulos y permite fecundacion y gestacion.",
    organs: ["Ovarios", "Trompas uterinas", "Utero", "Cervix", "Vagina"],
    keyFact: "El utero es un organo muscular donde puede desarrollarse el embrion.",
    question: "Como se conectan ovarios, trompas y utero?",
    miniSummary: "Produce gametos femeninos y permite la gestacion.",
  },
};

export const organInfo = {
  hair: { title: "Cabello", systemKey: "integumentary", description: "Ayuda a proteger zonas de la piel y participa en sensibilidad fina." },
  skin: { title: "Piel", systemKey: "integumentary", description: "Barrera protectora que regula temperatura y detecta estimulos." },
  glands: { title: "Glandulas cutaneas", systemKey: "integumentary", description: "Producen sudor o sebo para proteccion y regulacion." },
  skull: { title: "Craneo", systemKey: "skeletal", description: "Protege el encefalo y sostiene estructuras de la cara." },
  ribs: { title: "Caja toracica", systemKey: "skeletal", description: "Protege corazon y pulmones y participa en la respiracion." },
  spine: { title: "Columna vertebral", systemKey: "skeletal", description: "Sostiene el tronco y protege la medula espinal." },
  muscles: { title: "Musculatura", systemKey: "muscular", description: "Conjunto de musculos que permiten movimiento y postura." },
  tendons: { title: "Tendones", systemKey: "muscular", description: "Unen musculos con huesos para transmitir fuerza." },
  diaphragm: { title: "Diafragma", systemKey: "muscular", description: "Musculo clave para inspirar y espirar." },
  brain: { title: "Cerebro", systemKey: "nervous", description: "Procesa informacion y coordina conducta, memoria y movimiento." },
  spinalCord: { title: "Medula espinal", systemKey: "nervous", description: "Ruta principal de comunicacion entre encefalo y cuerpo." },
  nerves: { title: "Nervios", systemKey: "nervous", description: "Conectan organos, piel y musculos con el sistema nervioso central." },
  heart: { title: "Corazon", systemKey: "circulatory", description: "Bombea sangre hacia pulmones y hacia el resto del cuerpo." },
  arteries: { title: "Arterias", systemKey: "circulatory", description: "Llevan sangre desde el corazon hacia los tejidos." },
  veins: { title: "Venas", systemKey: "circulatory", description: "Devuelven sangre desde los tejidos hacia el corazon." },
  trachea: { title: "Traquea", systemKey: "respiratory", description: "Conduce aire hacia los bronquios." },
  lungs: { title: "Pulmones", systemKey: "respiratory", description: "Realizan el intercambio de oxigeno y dioxido de carbono." },
  bronchi: { title: "Bronquios", systemKey: "respiratory", description: "Distribuyen el aire dentro de los pulmones." },
  liver: { title: "Higado", systemKey: "digestive", description: "Produce bilis y procesa nutrientes absorbidos." },
  stomach: { title: "Estomago", systemKey: "digestive", description: "Mezcla alimentos con jugos gastricos." },
  intestines: { title: "Intestinos", systemKey: "digestive", description: "Absorben nutrientes, agua y forman desechos." },
  kidneys: { title: "Rinones", systemKey: "urinary", description: "Filtran sangre y producen orina." },
  bladder: { title: "Vejiga", systemKey: "urinary", description: "Almacena orina hasta su eliminacion." },
  ureters: { title: "Ureteres", systemKey: "urinary", description: "Conducen orina desde rinones hasta vejiga." },
  pituitary: { title: "Hipofisis", systemKey: "endocrine", description: "Coordina otras glandulas endocrinas." },
  thyroid: { title: "Tiroides", systemKey: "endocrine", description: "Regula metabolismo y crecimiento." },
  adrenals: { title: "Suprarrenales", systemKey: "endocrine", description: "Participan en respuesta al estres." },
  spleen: { title: "Bazo", systemKey: "lymphatic", description: "Filtra sangre y participa en defensas." },
  lymphNodes: { title: "Ganglios linfaticos", systemKey: "lymphatic", description: "Filtran linfa y concentran celulas inmunes." },
  thymus: { title: "Timo", systemKey: "lymphatic", description: "Participa en la maduracion de celulas defensivas." },
  prostate: { title: "Prostata", systemKey: "reproductiveMale", description: "Aporta liquido al semen." },
  testes: { title: "Testiculos", systemKey: "reproductiveMale", description: "Producen espermatozoides y hormonas." },
  ductus: { title: "Conductos deferentes", systemKey: "reproductiveMale", description: "Transportan espermatozoides." },
  ovaries: { title: "Ovarios", systemKey: "reproductiveFemale", description: "Producen ovulos y hormonas." },
  uterus: { title: "Utero", systemKey: "reproductiveFemale", description: "Organo donde puede desarrollarse el embrion." },
  uterineTubes: { title: "Trompas uterinas", systemKey: "reproductiveFemale", description: "Comunican ovarios y utero, y pueden ser sitio de fecundacion." },
};

export const organHotspots = {
  integumentary: [
    { organId: "hair", x: 58, y: 18 },
    { organId: "skin", x: 39, y: 42 },
    { organId: "glands", x: 62, y: 51 },
  ],
  skeletal: [
    { organId: "skull", x: 58, y: 20 },
    { organId: "ribs", x: 42, y: 36 },
    { organId: "spine", x: 58, y: 48 },
  ],
  muscular: [
    { organId: "muscles", x: 40, y: 36 },
    { organId: "tendons", x: 38, y: 67 },
    { organId: "diaphragm", x: 60, y: 45 },
  ],
  nervous: [
    { organId: "brain", x: 58, y: 18 },
    { organId: "spinalCord", x: 42, y: 39 },
    { organId: "nerves", x: 61, y: 52 },
  ],
  circulatory: [
    { organId: "heart", x: 59, y: 33 },
    { organId: "arteries", x: 42, y: 50 },
    { organId: "veins", x: 61, y: 57 },
  ],
  respiratory: [
    { organId: "trachea", x: 58, y: 28 },
    { organId: "bronchi", x: 42, y: 36 },
    { organId: "lungs", x: 61, y: 43 },
  ],
  digestive: [
    { organId: "liver", x: 39, y: 42 },
    { organId: "stomach", x: 61, y: 47 },
    { organId: "intestines", x: 50, y: 62 },
  ],
  urinary: [
    { organId: "kidneys", x: 40, y: 43 },
    { organId: "ureters", x: 60, y: 54 },
    { organId: "bladder", x: 50, y: 68 },
  ],
  endocrine: [
    { organId: "pituitary", x: 58, y: 18 },
    { organId: "thyroid", x: 42, y: 29 },
    { organId: "adrenals", x: 60, y: 44 },
  ],
  lymphatic: [
    { organId: "lymphNodes", x: 61, y: 38 },
    { organId: "spleen", x: 61, y: 48 },
    { organId: "thymus", x: 42, y: 33 },
  ],
  reproductiveMale: [
    { organId: "prostate", x: 50, y: 62 },
    { organId: "testes", x: 50, y: 72 },
    { organId: "ductus", x: 56, y: 58 },
  ],
  reproductiveFemale: [
    { organId: "ovaries", x: 45, y: 61 },
    { organId: "uterus", x: 50, y: 64 },
    { organId: "uterineTubes", x: 55, y: 60 },
  ],
};
