export const systemConfig = {
  integumentary: { label: "Tegumentario", color: "#e8b08d", opacity: 1 },
  skeletal: { label: "Oseo", color: "#f4f0df", opacity: 1 },
  muscular: { label: "Muscular", color: "#b73532", opacity: 1 },
  nervous: { label: "Nervioso", color: "#f0cf3e", opacity: 1 },
  circulatory: { label: "Circulatorio", color: "#c92f3a", opacity: 1 },
  respiratory: { label: "Respiratorio", color: "#67c7d8", opacity: 1 },
  digestive: { label: "Digestivo", color: "#c9792e", opacity: 1 },
  urinary: { label: "Urinario", color: "#d6bb4a", opacity: 1 },
  endocrine: { label: "Endocrino", color: "#8f6cc8", opacity: 1 },
  lymphatic: { label: "Linfatico", color: "#69b86f", opacity: 1 },
  reproductiveMale: { label: "Reprod. masc.", color: "#6c8fc7", opacity: 1 },
  reproductiveFemale: { label: "Reprod. fem.", color: "#d4719c", opacity: 1 },
};

export const systemOrder = [
  "integumentary",
  "skeletal",
  "muscular",
  "nervous",
  "circulatory",
  "respiratory",
  "digestive",
  "urinary",
  "endocrine",
  "lymphatic",
  "reproductiveMale",
  "reproductiveFemale",
];

export const modelAudit = {
  integumentary: {
    status: "ready",
    label: "Presentable",
    note: "Modelo aprobado para representar superficie corporal y piel.",
  },
  skeletal: {
    status: "ready",
    label: "Presentable",
    note: "Modelo Z-Anatomy restaurado. Buena base para explicar soporte, proteccion y movimiento.",
  },
  muscular: {
    status: "ready",
    label: "Presentable",
    note: "Modelo Z-Anatomy restaurado. Funciona bien como vista principal del sistema muscular.",
  },
  nervous: {
    status: "review",
    label: "En revision",
    note: "Modelo real con estructuras finas. Es util, pero puede exigir mas rendimiento en equipos lentos.",
  },
  circulatory: {
    status: "review",
    label: "En revision",
    note: "Modelo real con vasos finos. Usar solo modelo para proyectarlo con mejor lectura.",
  },
  respiratory: {
    status: "temporary",
    label: "Temporal",
    note: "Modelo provisorio. Falta reemplazarlo por un respiratorio 3D mas completo.",
  },
  digestive: {
    status: "review",
    label: "En revision",
    note: "Modelo 3D descargado e integrado. Falta revisar encuadre, materiales y licencia antes de marcarlo como presentable.",
  },
  urinary: {
    status: "review",
    label: "En revision",
    note: "Modelo 3D descargado e integrado. Es pesado, asi que conviene optimizarlo si ralentiza equipos lentos.",
  },
  endocrine: {
    status: "temporary",
    label: "Temporal",
    note: "Representa glandulas principales de forma general. Falta un modelo endocrino mas completo.",
  },
  lymphatic: {
    status: "placeholder",
    label: "Modelo temporal",
    note: "Se desactivo el GLB anterior porque se leia raro. Queda una vista temporal limpia hasta conseguir reemplazo.",
  },
  reproductiveMale: {
    status: "temporary",
    label: "Temporal",
    note: "Modelo provisorio. Falta reemplazarlo por un reproductor masculino 3D mas completo.",
  },
  reproductiveFemale: {
    status: "review",
    label: "En revision",
    note: "Modelo 3D descargado e integrado. Falta revisar encuadre, materiales y licencia antes de marcarlo como presentable.",
  },
};

export const systemDetails = {
  integumentary: {
    title: "Sistema tegumentario",
    summary: "Cubre el cuerpo y lo protege del exterior.",
    function: "Protege, regula temperatura y detecta tacto, dolor, presion y calor.",
    organs: ["Piel", "Cabello", "Unas", "Glandulas sudoriparas", "Glandulas sebaceas"],
    keyFact: "La piel es el organo mas extenso del cuerpo.",
    question: "Como ayuda la piel a regular la temperatura?",
    miniSummary: "Primera barrera de defensa y sensibilidad.",
    classroomStep: "Observa como la piel cubre todo el cuerpo y actua como frontera con el ambiente.",
    lookFor: ["La superficie que cubre todo el cuerpo.", "Zonas con pelo, unas y glandulas.", "Su relacion con sensibilidad y temperatura."],
  },
  skeletal: {
    title: "Sistema oseo",
    summary: "Sostiene, protege y da forma al cuerpo.",
    function: "Actua como armazon, protege organos y permite movimiento junto a los musculos.",
    organs: ["Craneo", "Columna vertebral", "Costillas", "Pelvis", "Huesos largos"],
    keyFact: "La medula osea produce celulas sanguineas.",
    question: "Que organos protege la caja toracica?",
    miniSummary: "Soporte, proteccion y movimiento.",
    classroomStep: "Identifica el esqueleto como armazon: sostiene, protege y permite movimiento.",
    lookFor: ["Craneo protegiendo el encefalo.", "Caja toracica alrededor de corazon y pulmones.", "Columna como eje del cuerpo."],
  },
  muscular: {
    title: "Sistema muscular",
    summary: "Produce movimiento, postura y calor.",
    function: "Sus contracciones mueven huesos, sostienen la postura y generan calor.",
    organs: ["Musculos esqueleticos", "Tendones", "Diafragma", "Musculos faciales"],
    keyFact: "El diafragma es un musculo esencial para la respiracion.",
    question: "Como se mueve un hueso cuando un musculo se contrae?",
    miniSummary: "Transforma energia en fuerza.",
    classroomStep: "Relaciona musculos, tendones y huesos: el movimiento ocurre cuando trabajan juntos.",
    lookFor: ["Grandes grupos musculares del tronco.", "Tendones cerca de manos y pies.", "Diafragma como musculo respiratorio."],
  },
  nervous: {
    title: "Sistema nervioso",
    summary: "Coordina informacion y respuestas.",
    function: "Recibe estimulos, procesa informacion y coordina respuestas del cuerpo.",
    organs: ["Cerebro", "Cerebelo", "Medula espinal", "Nervios perifericos"],
    keyFact: "La medula espinal comunica el encefalo con gran parte del cuerpo.",
    question: "Por que sacamos la mano rapido ante algo caliente?",
    miniSummary: "Control y comunicacion rapida.",
    classroomStep: "Sigue el camino de la informacion: cerebro, medula y nervios conectan todo el cuerpo.",
    lookFor: ["Cerebro como centro de procesamiento.", "Medula espinal como via principal.", "Nervios que llegan a extremidades."],
  },
  circulatory: {
    title: "Sistema circulatorio",
    summary: "Transporta sangre, gases y nutrientes.",
    function: "El corazon impulsa sangre para llevar oxigeno, nutrientes y retirar desechos.",
    organs: ["Corazon", "Arterias", "Venas", "Capilares", "Sangre"],
    keyFact: "En los capilares ocurre el intercambio con los tejidos.",
    question: "Por que los musculos necesitan sangre?",
    miniSummary: "Red de transporte del organismo.",
    classroomStep: "Mira la red de transporte: el corazon impulsa sangre por vasos hacia los tejidos.",
    lookFor: ["Corazon en el torax.", "Vasos que recorren brazos y piernas.", "Diferencia entre transportar y bombear."],
  },
  respiratory: {
    title: "Sistema respiratorio",
    summary: "Intercambia oxigeno y dioxido de carbono.",
    function: "Lleva aire a los pulmones para intercambiar oxigeno y dioxido de carbono.",
    organs: ["Nariz", "Laringe", "Traquea", "Bronquios", "Pulmones", "Diafragma"],
    keyFact: "El oxigeno pasa de los pulmones a la sangre.",
    question: "Como se relacionan los sistemas respiratorio y circulatorio?",
    miniSummary: "Intercambio de gases para obtener energia.",
    classroomStep: "Ubica el recorrido del aire hasta los pulmones y conectalo con la sangre.",
    lookFor: ["Traquea como tubo principal.", "Bronquios entrando a los pulmones.", "Pulmones como zona de intercambio."],
  },
  digestive: {
    title: "Sistema digestivo",
    summary: "Transforma los alimentos en nutrientes que el cuerpo puede aprovechar.",
    function: "Incorpora alimentos, los descompone, absorbe nutrientes y elimina residuos.",
    organs: ["Boca", "Faringe", "Esófago", "Estómago", "Hígado", "Páncreas", "Intestino delgado", "Intestino grueso"],
    keyFact: "La mayor parte de la absorción ocurre en el intestino delgado.",
    question: "¿Por qué no alcanza con comer y por qué hace falta digerir?",
    miniSummary: "Convierte alimentos en energia y materiales para las celulas.",
    classroomStep: "Sigue el recorrido del alimento y diferencia ingestión, digestión, absorción y eliminación.",
    lookFor: [
      "Boca y faringe como puerta de entrada del alimento.",
      "Estomago como zona de mezcla y formacion del quimo.",
      "Intestino delgado como lugar principal de absorcion.",
      "Higado y pancreas como organos anexos que ayudan a digerir.",
    ],
    guideFocus: [
      "Mostrar primero el recorrido general del alimento.",
      "Marcar la diferencia entre digestión mecánica y química.",
      "Señalar que absorber nutrientes no es lo mismo que eliminar residuos.",
    ],
    guideSequence: [
      "Introducción al sistema.",
      "Recorrido boca > faringe > esófago > estómago > intestino delgado > intestino grueso.",
      "Cierre con la idea de que el sistema prepara nutrientes para el resto del cuerpo.",
    ],
  },
  urinary: {
    title: "Sistema urinario",
    summary: "Filtra sangre y regula liquidos.",
    function: "Filtra sangre, produce orina y regula agua y sales.",
    organs: ["Rinones", "Ureteres", "Vejiga", "Uretra"],
    keyFact: "Los rinones ayudan a mantener el equilibrio interno.",
    question: "Por que filtrar la sangre es importante para todas las celulas?",
    miniSummary: "Filtrado y equilibrio interno.",
    classroomStep: "Observa como rinones, ureteres y vejiga forman un circuito de filtrado y salida.",
    lookFor: ["Rinones a ambos lados.", "Ureteres bajando hacia la vejiga.", "Vejiga como deposito temporal."],
  },
  endocrine: {
    title: "Sistema endocrino",
    summary: "Coordina procesos con hormonas.",
    function: "Libera hormonas que regulan crecimiento, metabolismo y reproduccion.",
    organs: ["Hipofisis", "Tiroides", "Pancreas endocrino", "Suprarrenales", "Gonadas"],
    keyFact: "Las hormonas son mensajes quimicos.",
    question: "Por que las hormonas viajan por la sangre?",
    miniSummary: "Mensajes quimicos de largo alcance.",
    classroomStep: "Piensa este sistema como mensajeria: glandulas pequeñas controlan procesos grandes.",
    lookFor: ["Hipofisis cerca del encefalo.", "Tiroides en el cuello.", "Suprarrenales sobre los rinones."],
  },
  lymphatic: {
    title: "Sistema linfatico",
    summary: "Defiende y recupera liquidos.",
    function: "Transporta linfa, filtra microorganismos y recupera liquidos.",
    organs: ["Vasos linfaticos", "Ganglios linfaticos", "Bazo", "Timo", "Amigdalas"],
    keyFact: "Los ganglios pueden inflamarse durante infecciones.",
    question: "Que funcion cumplen los ganglios?",
    miniSummary: "Defensa y drenaje de liquidos.",
    classroomStep: "Relaciona defensa y drenaje: la linfa se filtra en ganglios antes de volver a la sangre.",
    lookFor: ["Ganglios en cuello, axilas e ingle.", "Bazo y timo como organos defensivos.", "Red de drenaje de liquidos."],
  },
  reproductiveMale: {
    title: "Aparato reproductor masculino",
    summary: "Produce y transporta gametos masculinos.",
    function: "Produce espermatozoides y ayuda a transportarlos.",
    organs: ["Testiculos", "Epididimo", "Conductos deferentes", "Prostata", "Pene"],
    keyFact: "Los testiculos producen espermatozoides y hormonas.",
    question: "Por que la reproduccion requiere celulas especializadas llamadas gametos?",
    miniSummary: "Gametos masculinos y reproduccion.",
    classroomStep: "Identifica donde se producen, maduran y transportan los gametos masculinos.",
    lookFor: ["Testiculos como produccion de gametos.", "Conductos como via de transporte.", "Prostata como glandula auxiliar."],
  },
  reproductiveFemale: {
    title: "Aparato reproductor femenino",
    summary: "Produce ovulos y permite gestacion.",
    function: "Produce ovulos y permite fecundacion y gestacion.",
    organs: ["Ovarios", "Trompas uterinas", "Utero", "Cervix", "Vagina"],
    keyFact: "El utero es un organo muscular donde puede desarrollarse el embrion.",
    question: "Como se conectan ovarios, trompas y utero?",
    miniSummary: "Gametos femeninos y gestacion.",
    classroomStep: "Ubica ovarios, trompas y utero como partes conectadas de un mismo sistema.",
    lookFor: ["Ovarios a ambos lados.", "Trompas comunicando con el utero.", "Utero en el centro de la pelvis."],
  },
};

export const digestiveProcessSections = [
  {
    id: "mouth",
    title: "1. Boca: inicio de la digestión",
    image: "./assets/digestive/01-boca.svg",
    summary: "La cavidad oral es el primer tramo funcional del aparato digestivo.",
    body: "En la boca comienza la digestión mecánica con la masticación y la digestión química con la saliva. Los alimentos se mezclan, se humedecen y forman el bolo alimenticio.",
    bullets: ["Los dientes cortan, desgarran y trituran.", "La lengua mezcla el alimento con saliva.", "El bolo queda listo para ser deglutido."],
  },
  {
    id: "saliva",
    title: "2. Saliva, glándulas salivales y enzimas",
    image: "./assets/digestive/02-saliva.svg",
    summary: "La saliva lubrica, protege e inicia la digestión de carbohidratos.",
    body: "Las glándulas parótidas, submandibulares y sublinguales producen saliva. Además de agua, contiene mucinas, electrolitos y enzimas como la amilasa salival, que empieza a degradar almidones.",
    bullets: ["La saliva facilita la masticación y la deglución.", "La amilasa salival inicia la digestión química.", "En un adulto se produce alrededor de 1 a 1,5 litros diarios."],
  },
  {
    id: "swallowing",
    title: "3. Deglución: paso del bolo",
    image: "./assets/digestive/03-deglucion.svg",
    summary: "La deglución lleva el bolo desde la boca hacia el esófago.",
    body: "Primero hay una fase bucal voluntaria; luego, la fase faríngea y la esofágica son automáticas. La epiglotis ayuda a evitar que el alimento entre en la tráquea.",
    bullets: ["Fase bucal: se empuja el bolo hacia atrás.", "Fase faríngea: se protege la vía respiratoria.", "Fase esofágica: el bolo avanza hacia el estómago."],
  },
  {
    id: "esophagus",
    title: "4. Esófago y peristaltismo",
    image: "./assets/digestive/04-esofago.svg",
    summary: "El esófago transporta el bolo hacia el estómago.",
    body: "El esófago es un tubo muscular que no digiere ni absorbe nutrientes; su función principal es transportar el bolo mediante movimientos peristálticos coordinados.",
    bullets: ["Conecta faringe y estómago.", "Se ubica por detrás de la tráquea.", "El peristaltismo empuja el alimento hacia abajo."],
  },
  {
    id: "stomach",
    title: "5. Estómago: del bolo al quimo",
    image: "./assets/digestive/05-estomago.svg",
    summary: "El estómago mezcla el bolo con jugo gástrico.",
    body: "En el estómago ocurre digestión mecánica y química. El alimento se mezcla con jugos gástricos ácidos y enzimas, y se transforma en quimo, una mezcla semilíquida.",
    bullets: ["Actúa como reservorio temporal.", "Inicia la digestión de proteínas.", "Forma el quimo que pasará al intestino delgado."],
  },
  {
    id: "intestine",
    title: "6. Intestino delgado y órganos anexos",
    image: "./assets/digestive/06-intestino.svg",
    summary: "En el intestino delgado se completa gran parte de la digestión química.",
    body: "El quimo llega al duodeno y se mezcla con bilis y enzimas pancreáticas e intestinales. Allí se degradan carbohidratos, proteínas y lípidos en moléculas más simples.",
    bullets: ["El hígado produce bilis.", "El páncreas aporta enzimas digestivas.", "El duodeno recibe secreciones que ayudan a terminar la digestión."],
  },
  {
    id: "absorption",
    title: "7. Absorción de nutrientes",
    image: "./assets/digestive/08-absorcion.svg",
    summary: "Los nutrientes pasan del intestino delgado hacia la sangre y la linfa.",
    body: "Las paredes del intestino delgado tienen vellosidades que aumentan la superficie de contacto. Gracias a ellas, los nutrientes digeridos ingresan al organismo para ser transportados a las células.",
    bullets: ["La glucosa y aminoácidos pasan a la sangre.", "Los lípidos se relacionan con la linfa.", "La absorción permite aprovechar la energía de los alimentos."],
  },
  {
    id: "colon",
    title: "8. Intestino grueso: formación de heces",
    image: "./assets/digestive/07-intestino-grueso.svg",
    summary: "El intestino grueso recupera agua y forma las heces.",
    body: "Luego de la absorción de nutrientes, los restos no digeridos pasan al intestino grueso. Allí se reabsorbe agua, se compactan desechos y se forman las heces.",
    bullets: ["El colon reabsorbe agua.", "La microbiota participa en el proceso.", "Los desechos se compactan antes de eliminarse."],
  },
  {
    id: "egestion",
    title: "9. Defecación: salida de residuos",
    image: "./assets/digestive/09-defecacion.svg",
    summary: "La defecación elimina lo que el cuerpo no aprovechó.",
    body: "Las heces se almacenan temporalmente en el recto y salen por el ano. Es la etapa final del proceso digestivo y permite expulsar residuos no digeridos.",
    bullets: ["El recto almacena las heces.", "El ano regula la salida.", "No es absorción: es eliminación de residuos."],
  },
];

export const digestiveLessonSections = [
  {
    id: "intro",
    title: "Introducción: por qué necesitamos digerir",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Digestive%20system%20diagram%20es.svg",
    creditLabel: "Imagen abierta en español: Digestive system diagram es (Wikimedia Commons)",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Digestive_system_diagram_es.svg",
    summary: "El cuerpo necesita transformar los alimentos para obtener energia y materiales.",
    body: "Comer no alcanza por si solo. Los alimentos deben pasar por un recorrido donde se trituran, se mezclan con jugos digestivos y se convierten en nutrientes simples que las celulas pueden usar.",
    bullets: [
      "Los alimentos aportan energia para las funciones diarias.",
      "Tambien aportan materiales para crecer, reparar y mantener tejidos.",
      "Lo que no se aprovecha se elimina como residuo.",
    ],
  },
  {
    id: "general-process",
    title: "Proceso general: ingestión, digestión, absorción y egestión",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Digestive%20system%20diagram%20es.svg",
    creditLabel: "Imagen abierta en español: Digestive system diagram es (Wikimedia Commons)",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Digestive_system_diagram_es.svg",
    summary: "El proceso digestivo se puede entender en cuatro momentos principales.",
    body: "Primero el alimento ingresa por la boca. Luego se digiere, es decir, se transforma en sustancias mas simples. Despues se absorben nutrientes y agua. Finalmente se eliminan los restos no digeridos.",
    bullets: [
      "Ingestion: entrada del alimento.",
      "Digestion: transformacion mecanica y quimica.",
      "Absorcion y egestion: aprovechamiento y eliminacion.",
    ],
  },
  {
    id: "digestion-types",
    title: "Dos tipos de digestión",
    image: "./assets/digestive/12-tipos-digestion.svg",
    creditLabel: "Esquema adaptado para la unidad digestiva",
    creditUrl: "https://github.com/milton2112/atlas-3d-cuerpo-humano",
    summary: "La digestion mecanica prepara el alimento y la quimica lo descompone.",
    body: "La digestion mecanica fragmenta, tritura y mezcla. La digestion quimica cambia la composicion de los nutrientes gracias a enzimas y jugos digestivos. Las dos actuan juntas durante todo el recorrido.",
    bullets: [
      "Mecanica: masticacion, fragmentacion y mezclado.",
      "Quimica: enzimas que rompen moleculas complejas.",
      "Las dos se complementan, no funcionan por separado.",
    ],
  },
  {
    id: "mouth-parts",
    title: "Boca: partes principales",
    image: "./assets/digestive/16-boca-real.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "La boca es la puerta de entrada del sistema digestivo.",
    body: "En la boca se encuentran dientes, lengua y glandulas salivales. Ahi comienza la ingestion y tambien el primer tramo de la digestion mecanica y quimica.",
    bullets: [
      "Dientes: cortan, desgarran y trituran.",
      "Lengua: mezcla y acomoda el alimento.",
      "Glandulas salivales: vierten saliva.",
    ],
  },
  {
    id: "bolus",
    title: "Boca: bolo alimenticio",
    image: "./assets/digestive/17-bolo-alimenticio.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "El bolo alimenticio se forma en la boca.",
    body: "Los dientes trituran el alimento y la saliva lo humedece. La amilasa salival empieza a actuar sobre el almidon. Asi se forma una masa blanda llamada bolo alimenticio, lista para ser deglutida.",
    bullets: [
      "La masticacion es digestion mecanica.",
      "La saliva inicia digestion quimica.",
      "La lengua empuja el bolo hacia la faringe.",
    ],
  },
  {
    id: "teeth",
    title: "Boca: dientes",
    image: "./assets/digestive/18-dientes.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "Los dientes preparan el alimento para que siga el recorrido.",
    body: "Son estructuras muy duras. Los incisivos cortan, los caninos desgarran y los premolares y molares trituran y desmenuzan el alimento antes de la deglucion.",
    bullets: [
      "Incisivos: cortan.",
      "Caninos: desgarran.",
      "Premolares y molares: trituran.",
    ],
  },
  {
    id: "tongue",
    title: "Boca: lengua",
    image: "./assets/digestive/19-lengua.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "La lengua mezcla, acomoda y empuja el alimento.",
    body: "Es un organo musculoso que ubica el alimento entre los dientes durante la masticacion, lo mezcla con saliva y luego lo empuja hacia la faringe. Sus papilas gustativas ayudan a reconocer sabores.",
    bullets: [
      "Mezcla alimento y saliva.",
      "Ayuda a formar el bolo.",
      "Participa en la percepcion del sabor.",
    ],
  },
  {
    id: "pharynx",
    title: "Faringe y epiglotis",
    image: "./assets/digestive/20-faringe.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "La faringe conecta la boca con el esofago.",
    body: "Es una cavidad comun a los sistemas digestivo y respiratorio. Durante la deglucion, la epiglotis cubre la entrada de las vias respiratorias para evitar que el alimento entre en la traquea.",
    bullets: [
      "Conduce el bolo hacia el esofago.",
      "Tambien participa en el paso del aire.",
      "La epiglotis protege la via respiratoria.",
    ],
  },
  {
    id: "esophagus-lesson",
    title: "Esófago y movimientos peristálticos",
    image: "./assets/digestive/21-esofago.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "El esofago transporta el bolo hasta el estomago.",
    body: "Sus paredes realizan movimientos peristalticos, es decir, ondas de contraccion y relajacion muscular que empujan el alimento hacia abajo.",
    bullets: [
      "No absorbe nutrientes.",
      "Su funcion principal es transportar.",
      "El peristaltismo impulsa el alimento.",
    ],
  },
  {
    id: "stomach-lesson",
    title: "Estómago: formación del quimo",
    image: "./assets/digestive/22-estomago.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "En el estomago el bolo se mezcla con jugo gastrico.",
    body: "El estomago recibe el bolo por el cardias y lo mezcla con jugos gastricos. El acido clorhidrico, la pepsina y el moco ayudan a descomponer proteinas, destruir microorganismos y proteger la pared estomacal.",
    bullets: [
      "Cardias: entrada desde el esofago.",
      "Piloro: salida hacia el intestino delgado.",
      "Aqui se prepara el quimo.",
    ],
  },
  {
    id: "chyme",
    title: "Estómago: quimo",
    image: "./assets/digestive/23-quimo.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "El quimo es la mezcla resultante del trabajo del estomago.",
    body: "Cuando el alimento se bate con el jugo gastrico, se forma una masa semiliquida, espesa y acida llamada quimo. Luego pasa al duodeno a traves del piloro.",
    bullets: [
      "Se forma en el estomago.",
      "Tiene consistencia semiliquida.",
      "Pasa al duodeno por el piloro.",
    ],
  },
  {
    id: "small-intestine-lesson",
    title: "Intestino delgado: recorrido general",
    image: "./assets/digestive/24-intestino-delgado.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "En el intestino delgado se completa la digestion y se absorben nutrientes.",
    body: "Es un tubo largo con vellosidades intestinales. Se divide en duodeno, yeyuno e ileon. En el duodeno continua la digestion y en yeyuno e ileon se absorbe gran parte del contenido nutritivo.",
    bullets: [
      "Duodeno: continua al estomago.",
      "Yeyuno: zona intermedia.",
      "Ileon: comunica con el intestino grueso.",
    ],
  },
  {
    id: "digestive-juices",
    title: "Intestino delgado: bilis y jugos digestivos",
    image: "./assets/digestive/25-bilis.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "En el intestino delgado el quimo se mezcla con secreciones digestivas.",
    body: "La bilis, el jugo pancreatico y el jugo intestinal completan la digestion y ayudan a neutralizar la acidez del quimo que llega desde el estomago.",
    bullets: [
      "Bilis: ayuda con la digestion de grasas.",
      "Jugo pancreatico: aporta enzimas.",
      "Jugo intestinal: completa la digestion.",
    ],
  },
  {
    id: "chyle",
    title: "Intestino delgado: quilo y absorción",
    image: "./assets/digestive/26-quilo.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "Durante la absorcion, los nutrientes pasan desde el intestino al interior del cuerpo.",
    body: "Las vellosidades y microvellosidades aumentan la superficie de contacto. Gracias a ellas, los nutrientes atraviesan la pared intestinal y pasan a la sangre o, en algunos casos, a la linfa.",
    bullets: [
      "Las vellosidades aumentan la superficie de absorcion.",
      "Los nutrientes pasan a sangre o linfa.",
      "Luego se distribuyen a las celulas.",
    ],
  },
  {
    id: "large-intestine-lesson",
    title: "Intestino grueso",
    image: "./assets/digestive/27-intestino-grueso.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "El intestino grueso recupera agua y prepara la eliminacion.",
    body: "Recibe el material no digerible desde el ileon. Ahi se reabsorbe agua y algunos electrolitos. Los residuos se compactan, pasan por colon y recto y finalmente se eliminan.",
    bullets: [
      "Ciego, colon, recto y ano son sus partes principales.",
      "Recupera agua de los residuos.",
      "Forma y elimina las heces.",
    ],
  },
  {
    id: "annex-glands",
    title: "Glándulas anexas: saliva, hígado y páncreas",
    image: "./assets/digestive/28-glandulas-anexas.jpg",
    showImage: true,
    creditLabel: "Imagen incorporada para la unidad digestiva",
    creditUrl: "",
    summary: "Las glandulas anexas ayudan al tubo digestivo con secreciones y funciones de apoyo.",
    body: "Las glandulas salivales producen saliva. El higado produce bilis y participa en metabolismo, almacenamiento y desintoxicacion. El pancreas produce jugo pancreatico y tambien hormonas como insulina y glucagon.",
    bullets: [
      "Glandulas salivales: saliva.",
      "Higado: bilis y metabolismo.",
      "Pancreas: enzimas digestivas y hormonas.",
    ],
  },
];

export const systemLessonSections = {
  digestive: digestiveLessonSections,
};

export const digestiveRecapPoints = [
  "El alimento entra por la boca, se mastica y se mezcla con saliva hasta formar el bolo.",
  "La deglucion lleva el bolo por faringe y esofago hasta el estomago.",
  "En el estomago el bolo se mezcla con jugo gastrico y se transforma en quimo.",
  "En el intestino delgado actuan la bilis y los jugos digestivos; despues se absorben nutrientes.",
  "En el intestino grueso se recupera agua y se eliminan los residuos.",
];

export const digestiveReferenceLinks = [
  {
    label: "Digestive system diagram - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Digestive_system_diagram.png",
    note: "Vista general abierta del sistema digestivo.",
  },
  {
    label: "Salivary glands - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Salivary_glands.svg",
    note: "Referencia para glandulas salivales.",
  },
  {
    label: "Intestinal Villus (NIH BioArt 573)",
    url: "https://commons.wikimedia.org/wiki/File:Intestinal_Villus_(NIH_BioArt_573).png",
    note: "Referencia abierta para vellosidades intestinales.",
  },
  {
    label: "Types of teeth - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Types_of_teeth.svg",
    note: "Esquema abierto de incisivos, caninos y molares.",
  },
  {
    label: "Pharynx (PSF) - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Pharynx_(PSF).png",
    note: "Referencia para faringe y epiglotis.",
  },
  {
    label: "Pancreas (PSF) - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Pancreas_(PSF).png",
    note: "Referencia abierta para pancreas.",
  },
  {
    label: "Stomach diagram - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Stomach_diagram.svg",
    note: "Ilustracion abierta para estomago y formacion del quimo.",
  },
  {
    label: "Oesophagus - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Oesophagus.png",
    note: "Referencia abierta para esofago y transporte del bolo.",
  },
  {
    label: "Human tongue taste papillae - Wikimedia Commons",
    url: "https://commons.wikimedia.org/wiki/File:Human_tongue_taste_papillae.svg",
    note: "Referencia abierta para lengua y papilas gustativas.",
  },
];

export const organInfo = {
  hair: { title: "Cabello", systemKey: "integumentary", description: "Ayuda a proteger zonas de la piel y participa en sensibilidad fina." },
  skin: { title: "Piel", systemKey: "integumentary", description: "Barrera protectora que regula temperatura y detecta estimulos." },
  glands: { title: "Glandulas cutaneas", systemKey: "integumentary", description: "Producen sudor o sebo para proteccion y regulacion." },
  skull: { title: "Craneo", systemKey: "skeletal", description: "Protege el encefalo y sostiene estructuras de la cara." },
  ribs: { title: "Caja toracica", systemKey: "skeletal", description: "Protege corazon y pulmones y participa en la respiracion." },
  spine: { title: "Columna vertebral", systemKey: "skeletal", description: "Sostiene el tronco y protege la medula espinal." },
  muscles: { title: "Musculatura", systemKey: "muscular", description: "Conjunto de musculos que permiten movimiento y postura." },
  tendons: { title: "Tendones", systemKey: "muscular", description: "Unen musculos con huesos para transmitir fuerza." },
  diaphragm: { title: "Diafragma", systemKey: "muscular", description: "Musculo clave para inspirar y espirar." },
  brain: { title: "Cerebro", systemKey: "nervous", description: "Procesa informacion y coordina conducta, memoria y movimiento." },
  spinalCord: { title: "Medula espinal", systemKey: "nervous", description: "Ruta principal de comunicacion entre encefalo y cuerpo." },
  nerves: { title: "Nervios", systemKey: "nervous", description: "Conectan organos, piel y musculos con el sistema nervioso central." },
  heart: { title: "Corazon", systemKey: "circulatory", description: "Bombea sangre hacia pulmones y hacia el resto del cuerpo." },
  arteries: { title: "Arterias", systemKey: "circulatory", description: "Llevan sangre desde el corazon hacia los tejidos." },
  veins: { title: "Venas", systemKey: "circulatory", description: "Devuelven sangre desde los tejidos hacia el corazon." },
  trachea: { title: "Traquea", systemKey: "respiratory", description: "Conduce aire hacia los bronquios." },
  lungs: { title: "Pulmones", systemKey: "respiratory", description: "Realizan el intercambio de oxigeno y dioxido de carbono." },
  bronchi: { title: "Bronquios", systemKey: "respiratory", description: "Distribuyen el aire dentro de los pulmones." },
  mouth: { title: "Boca", systemKey: "digestive", description: "Permite la ingestión y mezcla el alimento con saliva." },
  teeth: { title: "Dientes", systemKey: "digestive", description: "Cortan, desgarran y trituran los alimentos." },
  tongue: { title: "Lengua", systemKey: "digestive", description: "Mezcla el alimento, ayuda a formar el bolo y participa en el gusto." },
  salivaryGlands: { title: "Glándulas salivales", systemKey: "digestive", description: "Producen saliva con amilasa para humedecer e iniciar la digestión." },
  pharynx: { title: "Faringe", systemKey: "digestive", description: "Conduce el bolo desde la boca hacia el esofago." },
  esophagus: { title: "Esófago", systemKey: "digestive", description: "Empuja el bolo al estómago mediante movimientos peristálticos." },
  liver: { title: "Hígado", systemKey: "digestive", description: "Produce bilis y participa en metabolismo, almacenamiento y desintoxicación." },
  pancreas: { title: "Páncreas", systemKey: "digestive", description: "Produce jugo pancreático y también hormonas como insulina y glucagón." },
  stomach: { title: "Estómago", systemKey: "digestive", description: "Mezcla el alimento con jugos gástricos y forma el quimo." },
  smallIntestine: { title: "Intestino delgado", systemKey: "digestive", description: "Completa gran parte de la digestion y absorbe la mayor parte de nutrientes." },
  largeIntestine: { title: "Intestino grueso", systemKey: "digestive", description: "Recupera agua y forma las heces antes de la eliminacion." },
  kidneys: { title: "Rinones", systemKey: "urinary", description: "Filtran sangre y producen orina." },
  bladder: { title: "Vejiga", systemKey: "urinary", description: "Almacena orina hasta su eliminacion." },
  ureters: { title: "Ureteres", systemKey: "urinary", description: "Conducen orina desde rinones hasta vejiga." },
  pituitary: { title: "Hipofisis", systemKey: "endocrine", description: "Coordina otras glandulas endocrinas." },
  thyroid: { title: "Tiroides", systemKey: "endocrine", description: "Regula metabolismo y crecimiento." },
  adrenals: { title: "Suprarrenales", systemKey: "endocrine", description: "Participan en respuesta al estres." },
  spleen: { title: "Bazo", systemKey: "lymphatic", description: "Filtra sangre y participa en defensas." },
  lymphNodes: { title: "Ganglios linfaticos", systemKey: "lymphatic", description: "Filtran linfa y concentran celulas inmunes." },
  thymus: { title: "Timo", systemKey: "lymphatic", description: "Participa en la maduracion de celulas defensivas." },
  prostate: { title: "Prostata", systemKey: "reproductiveMale", description: "Aporta liquido al semen." },
  testes: { title: "Testiculos", systemKey: "reproductiveMale", description: "Producen espermatozoides y hormonas." },
  ductus: { title: "Conductos deferentes", systemKey: "reproductiveMale", description: "Transportan espermatozoides." },
  ovaries: { title: "Ovarios", systemKey: "reproductiveFemale", description: "Producen ovulos y hormonas." },
  uterus: { title: "Utero", systemKey: "reproductiveFemale", description: "Organo donde puede desarrollarse el embrion." },
  uterineTubes: { title: "Trompas uterinas", systemKey: "reproductiveFemale", description: "Comunican ovarios y utero, y pueden ser sitio de fecundacion." },
};

export const organStudyInfo = {
  hair: { location: "Superficie de la piel.", function: "Protege y ayuda a percibir contacto.", keyFact: "No esta vivo en su parte visible." },
  skin: { location: "Cubre todo el cuerpo.", function: "Actua como barrera y regula temperatura.", keyFact: "Es el organo mas extenso." },
  glands: { location: "Dentro de la piel.", function: "Producen sudor o sebo.", keyFact: "Ayudan a enfriar y proteger la piel." },
  skull: { location: "Cabeza.", function: "Protege el encefalo.", keyFact: "Esta formado por varios huesos unidos." },
  ribs: { location: "Torax.", function: "Protegen corazon y pulmones.", keyFact: "Se mueven al respirar." },
  spine: { location: "Eje posterior del tronco.", function: "Sostiene y protege la medula espinal.", keyFact: "Esta formada por vertebras." },
  muscles: { location: "Distribuidos por todo el cuerpo.", function: "Generan movimiento y postura.", keyFact: "Trabajan junto a huesos y tendones." },
  tendons: { location: "Entre musculo y hueso.", function: "Transmiten fuerza al esqueleto.", keyFact: "Son muy resistentes." },
  diaphragm: { location: "Debajo de los pulmones.", function: "Permite la inspiracion.", keyFact: "Es clave para respirar." },
  brain: { location: "Dentro del craneo.", function: "Procesa informacion y coordina respuestas.", keyFact: "Consume mucha energia." },
  spinalCord: { location: "Dentro de la columna vertebral.", function: "Conecta encefalo y cuerpo.", keyFact: "Participa en reflejos." },
  nerves: { location: "Desde la medula hacia organos y extremidades.", function: "Transportan senales.", keyFact: "Permiten sensibilidad y movimiento." },
  heart: { location: "Centro del torax, levemente hacia la izquierda.", function: "Bombea sangre.", keyFact: "Late sin que tengamos que pensarlo." },
  arteries: { location: "Salen del corazon hacia tejidos.", function: "Distribuyen sangre.", keyFact: "Suelen soportar mas presion." },
  veins: { location: "Regresan desde tejidos al corazon.", function: "Devuelven sangre.", keyFact: "Muchas tienen valvulas." },
  trachea: { location: "Cuello y torax superior.", function: "Conduce aire.", keyFact: "Tiene anillos cartilaginosos." },
  lungs: { location: "Caja toracica.", function: "Intercambian gases.", keyFact: "Trabajan con el diafragma." },
  bronchi: { location: "Dentro de los pulmones.", function: "Reparten el aire.", keyFact: "Se ramifican como un arbol." },
  mouth: {
    location: "Cabeza, en la cavidad oral.",
    function: "Recibe el alimento e inicia la digestión mecánica y química.",
    keyFact: "En la boca se forma el bolo alimenticio gracias a dientes, lengua y saliva.",
  },
  teeth: {
    location: "En las arcadas dentarias de la cavidad oral.",
    function: "Cortan, desgarran y trituran el alimento antes de la deglución.",
    keyFact: "Incisivos cortan, caninos desgarran y molares trituran.",
  },
  tongue: {
    location: "En el piso de la boca.",
    function: "Mezcla el alimento con saliva, ayuda a formar el bolo y lo empuja hacia la faringe.",
    keyFact: "Sus papilas gustativas participan en la percepcion del sabor.",
  },
  salivaryGlands: {
    location: "Alrededor de la boca y la mandibula.",
    function: "Producen saliva para humedecer el alimento e iniciar la digestión del almidón.",
    keyFact: "La saliva contiene amilasa salival.",
  },
  pharynx: {
    location: "En el cuello, detras de la boca y la cavidad nasal.",
    function: "Conduce el bolo hacia el esófago durante la deglución.",
    keyFact: "La epiglotis evita que el alimento entre en la tráquea.",
  },
  esophagus: {
    location: "Entre la faringe y el estómago.",
    function: "Transporta el bolo por movimientos peristálticos.",
    keyFact: "No digiere ni absorbe: su tarea principal es trasladar.",
  },
  liver: {
    location: "Abdomen superior derecho, junto al estómago.",
    function: "Produce bilis y participa en metabolismo, almacenamiento y desintoxicación.",
    keyFact: "La bilis ayuda a la digestión de las grasas en el intestino delgado.",
  },
  pancreas: {
    location: "Debajo y detras del estomago.",
    function: "Produce jugo pancreático con enzimas digestivas y hormonas como insulina y glucagón.",
    keyFact: "Cumple una función digestiva y otra endocrina.",
  },
  stomach: {
    location: "Abdomen superior izquierdo.",
    function: "Mezcla el alimento con jugos gástricos y lo transforma en quimo.",
    keyFact: "Aquí empieza una digestión importante de las proteínas.",
  },
  smallIntestine: {
    location: "Centro del abdomen.",
    function: "Completa gran parte de la digestión y absorbe la mayor parte de los nutrientes.",
    keyFact: "Sus vellosidades y microvellosidades aumentan mucho la superficie de absorción.",
  },
  largeIntestine: {
    location: "Rodea al intestino delgado en el abdomen.",
    function: "Recupera agua y electrolitos y forma las heces.",
    keyFact: "Termina en recto y ano, donde se produce la eliminacion de residuos.",
  },
  kidneys: { location: "Parte posterior del abdomen.", function: "Filtran sangre.", keyFact: "Producen orina constantemente." },
  bladder: { location: "Pelvis.", function: "Almacena orina.", keyFact: "Se expande cuando se llena." },
  ureters: { location: "Entre rinones y vejiga.", function: "Conducen orina.", keyFact: "Usan movimientos musculares." },
  pituitary: { location: "Base del encefalo.", function: "Coordina glandulas.", keyFact: "Se la llama glandula maestra." },
  thyroid: { location: "Cuello anterior.", function: "Regula metabolismo.", keyFact: "Usa yodo para producir hormonas." },
  adrenals: { location: "Sobre los rinones.", function: "Participan en respuesta al estres.", keyFact: "Liberan adrenalina y otras hormonas." },
  spleen: { location: "Abdomen superior izquierdo.", function: "Filtra sangre y participa en defensas.", keyFact: "Ayuda a reciclar celulas sanguineas." },
  lymphNodes: { location: "Cuello, axilas, ingle y otras zonas.", function: "Filtran linfa.", keyFact: "Pueden inflamarse en infecciones." },
  thymus: { location: "Torax superior.", function: "Madura celulas defensivas.", keyFact: "Es mas activo en la infancia." },
  prostate: { location: "Debajo de la vejiga.", function: "Aporta liquido seminal.", keyFact: "Rodea parte de la uretra." },
  testes: { location: "Escroto.", function: "Producen espermatozoides y testosterona.", keyFact: "Funcionan mejor a menor temperatura corporal." },
  ductus: { location: "Desde testiculos hacia pelvis.", function: "Transportan espermatozoides.", keyFact: "Forman parte del recorrido del semen." },
  ovaries: { location: "Pelvis, a ambos lados del utero.", function: "Producen ovulos y hormonas.", keyFact: "Tienen ciclos de maduracion." },
  uterus: { location: "Pelvis.", function: "Puede alojar el desarrollo embrionario.", keyFact: "Es muscular y cambia de tamano." },
  uterineTubes: { location: "Entre ovarios y utero.", function: "Comunican y transportan el ovulo.", keyFact: "Alli puede ocurrir fecundacion." },
};

export const organHotspots = {
  integumentary: [
    { organId: "hair", x: 58, y: 18 },
    { organId: "skin", x: 39, y: 42 },
    { organId: "glands", x: 62, y: 51 },
  ],
  skeletal: [
    { organId: "skull", x: 58, y: 20 },
    { organId: "ribs", x: 42, y: 36 },
    { organId: "spine", x: 58, y: 48 },
  ],
  muscular: [
    { organId: "muscles", x: 40, y: 36 },
    { organId: "tendons", x: 38, y: 67 },
    { organId: "diaphragm", x: 60, y: 45 },
  ],
  nervous: [
    { organId: "brain", x: 58, y: 18 },
    { organId: "spinalCord", x: 42, y: 39 },
    { organId: "nerves", x: 61, y: 52 },
  ],
  circulatory: [
    { organId: "heart", x: 59, y: 33 },
    { organId: "arteries", x: 42, y: 50 },
    { organId: "veins", x: 61, y: 57 },
  ],
  respiratory: [
    { organId: "trachea", x: 58, y: 28 },
    { organId: "bronchi", x: 42, y: 36 },
    { organId: "lungs", x: 61, y: 43 },
  ],
  digestive: [
    { organId: "esophagus", nx: 0.49, ny: 0.81, nz: 0.69 },
    { organId: "liver", nx: 0.31, ny: 0.54, nz: 0.80 },
    { organId: "stomach", nx: 0.69, ny: 0.45, nz: 0.79 },
    { organId: "pancreas", nx: 0.47, ny: 0.39, nz: 0.52 },
    { organId: "smallIntestine", nx: 0.52, ny: 0.31, nz: 0.80 },
    { organId: "largeIntestine", nx: 0.77, ny: 0.39, nz: 0.82 },
  ],
  urinary: [
    { organId: "kidneys", x: 40, y: 43 },
    { organId: "ureters", x: 60, y: 54 },
    { organId: "bladder", x: 50, y: 68 },
  ],
  endocrine: [
    { organId: "pituitary", x: 58, y: 18 },
    { organId: "thyroid", x: 42, y: 29 },
    { organId: "adrenals", x: 60, y: 44 },
  ],
  lymphatic: [
    { organId: "lymphNodes", x: 61, y: 38 },
    { organId: "spleen", x: 61, y: 48 },
    { organId: "thymus", x: 42, y: 33 },
  ],
  reproductiveMale: [
    { organId: "prostate", x: 50, y: 62 },
    { organId: "testes", x: 50, y: 72 },
    { organId: "ductus", x: 56, y: 58 },
  ],
  reproductiveFemale: [
    { organId: "ovaries", x: 45, y: 61 },
    { organId: "uterus", x: 50, y: 64 },
    { organId: "uterineTubes", x: 55, y: 60 },
  ],
};

Object.assign(modelAudit.digestive, {
  note: "Modelo 3D funcional para estudiar el recorrido. Conviene seguir puliendo encuadre y materiales.",
});

Object.assign(systemDetails.digestive, {
  organs: ["Boca", "Faringe", "Esofago", "Estomago", "Higado", "Pancreas", "Intestino delgado", "Intestino grueso"],
  keyFact: "La mayor parte de la absorcion ocurre en el intestino delgado.",
  question: "Por que no alcanza con comer y por que hace falta digerir?",
  classroomStep: "Sigue el recorrido del alimento y diferencia ingestion, digestion, absorcion y eliminacion.",
  guideFocus: [
    "Mostrar primero el recorrido general del alimento.",
    "Marcar la diferencia entre digestion mecanica y quimica.",
    "Senalar que absorber nutrientes no es lo mismo que eliminar residuos.",
  ],
  guideSequence: [
    "Introduccion al sistema y proceso general.",
    "Recorrido boca > faringe > esofago > estomago > intestino delgado > intestino grueso.",
    "Cierre con la idea de que el sistema prepara nutrientes para el resto del cuerpo.",
  ],
  processTimeline: [
    "Boca -> faringe -> esofago",
    "Estomago -> formacion del quimo",
    "Intestino delgado -> digestion final y absorcion",
    "Intestino grueso -> recuperacion de agua y eliminacion",
  ],
  organMap: [
    "Boca: ingresa el alimento y se forma el bolo.",
    "Esofago: transporta el bolo al estomago.",
    "Estomago: mezcla y forma el quimo.",
    "Higado y pancreas: aportan secreciones para digerir.",
    "Intestino delgado: absorbe la mayor parte de nutrientes.",
    "Intestino grueso: recupera agua y forma las heces.",
  ],
});

Object.assign(organInfo, {
  mouth: { title: "Boca", systemKey: "digestive", description: "Permite la ingestion y mezcla el alimento con saliva." },
  salivaryGlands: { title: "Glandulas salivales", systemKey: "digestive", description: "Producen saliva con amilasa para humedecer e iniciar la digestion." },
  esophagus: { title: "Esofago", systemKey: "digestive", description: "Empuja el bolo al estomago mediante movimientos peristalticos." },
  liver: { title: "Higado", systemKey: "digestive", description: "Produce bilis y participa en metabolismo, almacenamiento y desintoxicacion." },
  pancreas: { title: "Pancreas", systemKey: "digestive", description: "Produce jugo pancreatico y tambien hormonas como insulina y glucagon." },
  stomach: { title: "Estomago", systemKey: "digestive", description: "Mezcla el alimento con jugos gastricos y forma el quimo." },
});

Object.assign(organStudyInfo, {
  mouth: {
    location: "Cabeza, en la cavidad oral.",
    function: "Recibe el alimento e inicia la digestion mecanica y quimica.",
    keyFact: "En la boca se forma el bolo alimenticio gracias a dientes, lengua y saliva.",
  },
  teeth: {
    location: "En las arcadas dentarias de la cavidad oral.",
    function: "Cortan, desgarran y trituran el alimento antes de la deglucion.",
    keyFact: "Incisivos cortan, caninos desgarran y molares trituran.",
  },
  tongue: {
    location: "En el piso de la boca.",
    function: "Mezcla el alimento con saliva, ayuda a formar el bolo y lo empuja hacia la faringe.",
    keyFact: "Sus papilas gustativas participan en la percepcion del sabor.",
  },
  salivaryGlands: {
    location: "Alrededor de la boca y la mandibula.",
    function: "Producen saliva para humedecer el alimento e iniciar la digestion del almidon.",
    keyFact: "La saliva contiene amilasa salival.",
  },
  pharynx: {
    location: "En el cuello, detras de la boca y la cavidad nasal.",
    function: "Conduce el bolo hacia el esofago durante la deglucion.",
    keyFact: "La epiglotis evita que el alimento entre en la traquea.",
  },
  esophagus: {
    location: "Entre la faringe y el estomago.",
    function: "Transporta el bolo por movimientos peristalticos.",
    keyFact: "No digiere ni absorbe: su tarea principal es trasladar.",
  },
  liver: {
    location: "Abdomen superior derecho, junto al estomago.",
    function: "Produce bilis y participa en metabolismo, almacenamiento y desintoxicacion.",
    keyFact: "La bilis ayuda a la digestion de las grasas en el intestino delgado.",
  },
  pancreas: {
    location: "Debajo y detras del estomago.",
    function: "Produce jugo pancreatico con enzimas digestivas y hormonas como insulina y glucagon.",
    keyFact: "Cumple una funcion digestiva y otra endocrina.",
  },
  stomach: {
    location: "Abdomen superior izquierdo.",
    function: "Mezcla el alimento con jugos gastricos y lo transforma en quimo.",
    keyFact: "Aqui empieza una digestion importante de las proteinas.",
  },
  smallIntestine: {
    location: "Centro del abdomen.",
    function: "Completa gran parte de la digestion y absorbe la mayor parte de los nutrientes.",
    keyFact: "Sus vellosidades y microvellosidades aumentan mucho la superficie de absorcion.",
  },
});

const digestivoTitles = {
  intro: "Introduccion: por que necesitamos digerir",
  "general-process": "Proceso general: ingestion, digestion, absorcion y egestion",
  "digestion-types": "Dos tipos de digestion",
  "esophagus-lesson": "Esofago y movimientos peristalticos",
  "stomach-lesson": "Estomago: formacion del quimo",
  chyme: "Estomago: quimo",
  chyle: "Intestino delgado: quilo y absorcion",
  "annex-glands": "Glandulas anexas: saliva, higado y pancreas",
};

digestiveLessonSections.forEach((section) => {
  if (digestivoTitles[section.id]) section.title = digestivoTitles[section.id];
});

Object.assign(systemDetails.digestive, {
  summary: "Convierte alimentos en nutrientes y elimina residuos.",
  description:
    "El sistema digestivo incorpora alimentos, los transforma en sustancias mas simples, absorbe nutrientes y elimina lo que el cuerpo no puede aprovechar.",
  function: "Descompone alimentos, absorbe nutrientes y elimina residuos.",
  miniSummary: "Transforma alimentos en nutrientes para las celulas.",
  introHighlights: [
    "Permite obtener energia y materiales a partir de los alimentos.",
    "Combina acciones mecanicas, quimicas y de absorcion.",
    "Se organiza como un recorrido desde la boca hasta la eliminacion.",
  ],
  lookFor: [
    "Boca y faringe como ingreso del alimento.",
    "Estomago como zona de mezcla y formacion del quimo.",
    "Intestino delgado como principal zona de absorcion.",
    "Intestino grueso como tramo de recuperacion de agua.",
  ],
  guideFocus: [
    "Primero mostrar el recorrido completo del alimento.",
    "Diferenciar digestion mecanica y quimica sin mezclar conceptos.",
    "Remarcar que absorber nutrientes no es lo mismo que eliminar residuos.",
  ],
  guideSequence: [
    "Comenzar por la introduccion al sistema y su funcion general.",
    "Abrir la secuencia paso a paso para seguir el alimento.",
    "Volver al modelo y senalar los organos principales.",
    "Cerrar con el resumen final del proceso completo.",
  ],
});

const digestiveLessonOverrides = {
  intro: {
    summary: "Antes de absorber nutrientes, el cuerpo necesita transformar los alimentos.",
    body:
      "El alimento no puede ser aprovechado tal como entra. A lo largo del tubo digestivo se tritura, se mezcla con secreciones y se convierte en nutrientes simples que pueden llegar a las celulas.",
    bullets: [
      "Los alimentos aportan energia para las funciones diarias.",
      "Tambien aportan materiales para crecer, reparar y mantener tejidos.",
      "Lo que no se aprovecha termina eliminandose como residuo.",
    ],
    classroomSummary: "El cuerpo necesita transformar los alimentos antes de poder usarlos.",
  },
  "general-process": {
    summary: "El proceso digestivo se entiende mejor si se divide en cuatro momentos.",
    body:
      "Primero el alimento entra por la boca. Despues se digiere, luego se absorben nutrientes y agua, y finalmente se eliminan los restos no aprovechables.",
    bullets: [
      "Ingestion: entrada del alimento.",
      "Digestion: transformacion mecanica y quimica.",
      "Absorcion: paso de nutrientes y agua al interior del cuerpo.",
      "Egestion: eliminacion de residuos.",
    ],
    classroomSummary: "Ingreso, digestion, absorcion y eliminacion forman el recorrido basico del sistema.",
  },
  "digestion-types": {
    summary: "La digestion mecanica prepara el alimento y la quimica lo descompone.",
    body:
      "La digestion mecanica corta, tritura y mezcla. La digestion quimica rompe moleculas complejas gracias a enzimas y jugos digestivos. Las dos actuan juntas durante todo el recorrido.",
    bullets: [
      "Mecanica: masticacion, fragmentacion y mezclado.",
      "Quimica: enzimas y jugos que transforman nutrientes.",
      "Ambas trabajan de forma complementaria.",
    ],
    classroomSummary: "Mecanica y quimica actuan juntas para volver util el alimento.",
  },
  "mouth-parts": {
    classroomSummary: "En la boca empieza la ingestion y se activa la primera digestion.",
  },
  bolus: {
    classroomSummary: "El bolo alimenticio se forma por la accion conjunta de dientes, lengua y saliva.",
  },
  teeth: {
    classroomSummary: "Los dientes cortan, desgarran y trituran antes de la deglucion.",
  },
  tongue: {
    classroomSummary: "La lengua mezcla, acomoda y empuja el alimento hacia la faringe.",
  },
  pharynx: {
    classroomSummary: "La faringe conduce el bolo y la epiglotis protege la via respiratoria.",
  },
  "esophagus-lesson": {
    classroomSummary: "El esofago transporta el bolo con movimientos peristalticos.",
  },
  "stomach-lesson": {
    classroomSummary: "En el estomago el alimento se mezcla con jugos gastricos y empieza la formacion del quimo.",
  },
  chyme: {
    classroomSummary: "El quimo es la mezcla semiliquida que sale del estomago hacia el duodeno.",
  },
  "small-intestine-lesson": {
    classroomSummary: "En el intestino delgado se completa la digestion y se absorbe la mayor parte de los nutrientes.",
  },
  "digestive-juices": {
    classroomSummary: "La bilis y los jugos digestivos completan la digestion dentro del intestino delgado.",
  },
  chyle: {
    classroomSummary: "La absorcion permite que los nutrientes pasen a sangre o linfa.",
  },
  "large-intestine-lesson": {
    classroomSummary: "En el intestino grueso se recupera agua y se forman los residuos finales.",
  },
  "annex-glands": {
    summary: "Las glandulas anexas ayudan a la digestion aunque el alimento no pase por dentro de ellas.",
    body:
      "Las glandulas salivales, el higado y el pancreas producen secreciones que desembocan en distintos tramos del tubo digestivo y facilitan la digestion.",
    bullets: [
      "Las glandulas salivales producen saliva con amilasa.",
      "El higado produce bilis para ayudar con las grasas.",
      "El pancreas libera jugo pancreatico con enzimas digestivas.",
    ],
    classroomSummary: "Las glandulas anexas aportan secreciones clave para completar la digestion.",
  },
};

digestiveLessonSections.forEach((section) => {
  const override = digestiveLessonOverrides[section.id];
  if (override) Object.assign(section, override);
});
